# .github/workflows/arise-deploy.yml
name: Deploy Arise to html branch

on:
  # Runs on pushes targeting the default branch
  # Only runs when the push contains changes to the site source itself. No need to rebuild the site if it's just program files that have changed.
  push:
    branches: ["main"]
    paths: ['arise-source/**']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    name: Deploy Arise
    steps:
      - name: git-checkout
        uses: actions/checkout@v2

      - name: Install pandoc
        run: sudo apt-get install -y pandoc

      - name: Build Arise
        run: bash arise build
    
      - name: Push to live branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: html # Feel free to change this. This is where Arise artefacts will be pushed.
          FOLDER: arise-out # The Arise build output location. Don't change this.
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Handled automatically -- Don't change this unless you're pushing to a different repo
          MESSAGE: "Commit: ({sha}) {msg}" # Copies commit msg from main to the deploy version branch
